name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Inputing "the quick Brown Fox jumps Over the Lazy Dog."
      id: inputing-the-quick-brown-fox-jumps-over-the-lazy-dog
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputing "the quick Brown Fox jumps Over the Lazy Dog."
        setup-command: ''
        command: python3 regex_capital_words/main.py
        input: the quick Brown Fox jumps Over the Lazy Dog.
        expected-output: |-
          Brown
          Fox
          Over
          Lazy
          Dog
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Inputting "Alice and Bob went to New York City to meet Charlie."
      id: inputting-alice-and-bob-went-to-new-york-city-to-meet-charlie
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "Alice and Bob went to New York City to meet Charlie."
        setup-command: ''
        command: python3 regex_capital_words/main.py
        input: Alice and Bob went to New York City to meet Charlie.
        expected-output: |-
          Alice
          Bob
          New
          York
          City
          Charlie
        comparison-method: exact
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INPUTING-THE-QUICK-BROWN-FOX-JUMPS-OVER-THE-LAZY-DOG_RESULTS: "${{steps.inputing-the-quick-brown-fox-jumps-over-the-lazy-dog.outputs.result}}"
        INPUTTING-ALICE-AND-BOB-WENT-TO-NEW-YORK-CITY-TO-MEET-CHARLIE_RESULTS: "${{steps.inputting-alice-and-bob-went-to-new-york-city-to-meet-charlie.outputs.result}}"
      with:
        runners: inputing-the-quick-brown-fox-jumps-over-the-lazy-dog,inputting-alice-and-bob-went-to-new-york-city-to-meet-charlie
